### PR TITLE
added .travis.yml and ataru to Gemfile

### PR DESCRIPTION
**Pull request by madziaf**

### CODE REVIEW

**Comment by moonglum** [comment]
I'm a little confused! Why did you add ataru to its own Gemfile?

**Comment by madziaf** [comment]
@moonglum welcome to the moon, PadawansMoon :)

**Comment by moonglum** [comment]
@madziaf Sorry :laughing: I have to read the notifications / title of the page more carefully :laughing:

**Comment by moonglum** [comment]
Then I would say: This looks pretty good, and Travis really likes it :smile:

**Comment by madziaf** [comment]
So I need to change, so it doesn't like it anymore and shows some interesting output. Hopefully.
Destroy, destroy!!

**Comment by moonglum** [comment]
:rage2: "@madziaf has gone into rampage" :rage4:

**Comment by moonglum** [comment]
```
# Running:

F

Finished in 0.010800s, 92.5952 runs/s, 92.5952 assertions/s.

1) Failure:

#<Class:0x00000003089500>#test_README_0 [README.md:16]:

Expected: 24

Actual: 42

1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

:dancers:

**Comment by madziaf** [comment]
@moonglum can you see it on travis?
where do you find it?

**Comment by madziaf** [comment]
ok, found it:) amazing!!

**Pull request closed without merging**
